import type { RideDefinition } from '@/types/game';

export const RIDE_DEFINITIONS: RideDefinition[] = [
  {
    id: 'ferris_wheel',
    name: 'Ferris Wheel',
    emoji: '🎡',
    baseCost: 100,
    baseIncome: 1,
    baseCapacity: 8,
    category: 'gentle',
  },
  {
    id: 'bumper_cars',
    name: 'Bumper Cars',
    emoji: '🚗',
    baseCost: 200,
    baseIncome: 2,
    baseCapacity: 10,
    category: 'family',
  },
  {
    id: 'tea_cups',
    name: 'Tea Cups',
    emoji: '🍵',
    baseCost: 300,
    baseIncome: 3,
    baseCapacity: 12,
    category: 'gentle',
  },
  {
    id: 'carousel',
    name: 'Carousel',
    emoji: '🎠',
    baseCost: 400,
    baseIncome: 4,
    baseCapacity: 14,
    category: 'family',
  },
  {
    id: 'log_flume',
    name: 'Log Flume',
    emoji: '🪵',
    baseCost: 500,
    baseIncome: 5,
    baseCapacity: 6,
    category: 'water',
  },
  {
    id: 'haunted_house',
    name: 'Haunted House',
    emoji: '👻',
    baseCost: 600,
    baseIncome: 6,
    baseCapacity: 10,
    category: 'thrill',
  },
  {
    id: 'pirate_ship',
    name: 'Pirate Ship',
    emoji: '🏴‍☠️',
    baseCost: 700,
    baseIncome: 7,
    baseCapacity: 16,
    category: 'thrill',
  },
  {
    id: 'drop_tower',
    name: 'Drop Tower',
    emoji: '🗼',
    baseCost: 900,
    baseIncome: 9,
    baseCapacity: 7,
    category: 'thrill',
  },
  {
    id: 'water_slide',
    name: 'Water Slide',
    emoji: '🌊',
    baseCost: 1000,
    baseIncome: 10,
    baseCapacity: 9,
    category: 'water',
  },
  {
    id: 'spinning_coaster',
    name: 'Spinning Coaster',
    emoji: '🌀',
    baseCost: 1200,
    baseIncome: 13,
    baseCapacity: 10,
    category: 'thrill',
  },
  {
    id: 'roller_coaster',
    name: 'Roller Coaster',
    emoji: '🎢',
    baseCost: 1500,
    baseIncome: 16,
    baseCapacity: 14,
    category: 'thrill',
  },
];

export const getRideDefinition = (id: string): RideDefinition | undefined => RIDE_DEFINITIONS.find((r) => r.id === id);
